create table "DEMO_CUSTOMERS" (
    "CUSTOMER_ID"         number generated by default on null as identity,
    "CUST_FIRST_NAME"     varchar2(20 char) not null,
    "CUST_LAST_NAME"      varchar2(20 char) not null,
    "CUST_STREET_ADDRESS1"varchar2(60 char),
    "CUST_STREET_ADDRESS2"varchar2(60 char),
    "CUST_CITY"           varchar2(30 char),
    "CUST_STATE"          varchar2(2 char),
    "CUST_POSTAL_CODE"    varchar2(10 char),
    "CUST_EMAIL"          varchar2(30 char),
    "PHONE_NUMBER1"       varchar2(15 char),
    "PHONE_NUMBER2"       varchar2(15 char),
    "URL"                 varchar2(100 char),
    "CREDIT_LIMIT"        number(11,2),
    "TAGS"                varchar2(4000 char),
    constraint "DEMO_CUSTOMERS_PK" primary key ( "CUSTOMER_ID" )
);

comment on table "DEMO_CUSTOMERS" is 'TABLE FOR STORING CUSTOMERS DATA';